name = "hex-edge"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "c08578525b891edc13c8187ab8e78d53"
zone_id = "84460b743cd17a92f2b921f9138a3cd0"

# Required for local dev in 1.15.0 of Wrangler
workers_dev = true

[dev]
port=9000

[env.dev]
name = "hex-dev"
route = "api.hexahedron.io/dev/*"
workers_dev = false

[env.staging]
name = "hex-staging"
route = "api.hexahedron.io/staging/*"
workers_dev = false

[env.production]
name = "hex-production"
route = "api.hexahedron.io/prod/*"
workers_dev = false
