name: Deploy Cloudflare Worker
on:
  push:
    paths:
      - "services/api/**"
      - ".github/workflows/api-deploy.yml"
    branches:
      - staging
      - main
      - development

jobs:
  deploy:
    name: API Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Set Fauna Access Key
        uses: iamtheyammer/branch-env-vars@v1.0.2
        with:
          bevActionOnNoRef: error
          FAUNA_ACCESS_KEY: |
            main:${{ secrets.MAIN_FAUNA_ACCESS_KEY }}
            staging:${{ secrets.STAGING_FAUNA_ACCESS_KEY }}
            development:${{ secrets.DEV_FAUNA_ACCESS_KEY }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Update NPM
        run: npm install -g npm@latest

      - name: Setup Project
        run: cd services/api && npm install

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.WRANGLER_TOKEN }}
          environment: ${{ env.GITHUB_REF_SLUG }}
          workingDirectory: 'services/api'
        env:
          FAUNA_ACCESS_KEY: ${{ env.FAUNA_ACCESS_KEY }}